### PR TITLE
Update to PHP 8

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by zzjin** [comment]
need any update to merge?

**Comment by TimWolla** [comment]
PHP 8 does not bring any benefit for this Docker image, because it is not meant to run custom software. It however possibly introduces breakage. Thus I plan on sitting on this PR for a little longer to make sure any PHP bugs and Adminer incompatibilities are fixed.

**Comment by TimWolla** [comment]
@guilliamxavier There's also #108. I was hoping to sit that out, because at least #108 is a not-as-severe issue. But Adminer returning incorrect or missing information is bad of course. I'll try to get a revert done this evening.

**Comment by guilliamxavier** [comment]
My bad, the "tables status is all empty cells" regression is not because of PHP 8 but Adminer 4.8.1, as downgrading to 4.8.0 fixes it 😖

**Pull request merged**
