### PR TITLE
For the cases where there are no root rights

### PR DESCRIPTION
**Pull request by motorox**
In cloud (k8, openshift) i had an issue to deploy the container with plugins.
The entrypoint.sh gave an error trying to copy the plugin file.

### CODE REVIEW

**Comment by TimWolla** [comment]
Hi! Thanks for the contribution. However I don't see why this would be necessary. Adminer does not run as root. There's a `USER adminer` command at the bottom of the Dockerfile: https://github.com/TimWolla/docker-adminer/blob/acc5bbbda499f70e8028376d63e2fe4758d09bf4/4/Dockerfile#L58 and `/var/www/html/plugins-enabled` is properly owned by that user.

**Comment by motorox** [comment]
It happened to me, that i could not deploy in kubernetes/openshift the container. It crashed, when entrypoint.sh tried to copy the required plugins.

**Comment by TimWolla** [comment]
Is your execution environment forcing a different user when running a container based on this image? Then it's clear that the directory is not writable.

However the correct fix is not opening up the permissions to make the directory world writable for every user of this image. Instead you should either make sure that your execution environment uses the correct user (`adminer`) or run a custom image `FROM adminer` that has appropriate permissions for the `plugins-enabled` directory.

**Comment by motorox** [comment]
On my POD, when do a 'whoami' i get this:
whoami: unknown uid 1016030000 
The uid is random each time the pod restarts. 
You can close/reject this PR if not suitable.
Thanks.

**Pull request closed without merging**
